version: '3.7'

volumes:
    mysql:
        driver: local

services:
    db:
        image: mysql:5.7.29
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '3306:3306'
        expose:
            - '3306'
    php:
        build:
            context: ./Docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        working_dir: /var/www/laravel
        volumes:
            - ./:/var/www/laravel
            - ./logs/laravel:/var/www/app/logs
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    nginx:
        build: ./Docker/nginx
        ports:
            - 80:80
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./:/var/www/laravel
            - ./logs/laravel:/var/www/app/logs
